dist: xenial
language: php
php:
  - '5.6'

jobs:
  include:
    - language: python
      python:  3.6      
      install:
      - pip install -r requirements.txt
      script:
        - coverage run -m pytest -W ignore::DeprecationWarning
        - coverage report --include="./rest-api/*"

    - language: node_js
      node_js: node
      before_install:
        - npm i -g npm@6.14.10
      install: 
        - npm install react-bootstrap-validation
        - npm install react-bootstrap
        - npm install react-horizontal-scrolling-menu
        - npm install axios 
        - npm install enzyme
        - npm install enzyme-adapter-react-16
        - npm install framer-motion
      cache: npm
      script:
        - npm test



  
