dist: xenial
language: php
php:
  - '5.6'

jobs:
  include:
    - language: python
      python:  3.6      

    # command to install dependencies
      install:
      - pip install -r requirements.txt

    # command to run tests
      script:
        - coverage run -m pytest -W ignore::DeprecationWarning
        - coverage report --include="./rest-api/*"

    - language: node_js
      node_js: 12
      before_install:
        - npm i -g npm@6.14.10
      cache: npm
      install: 
        - npm install react-bootstrap-validation --save
        - npm install bootstrap --save
        - npm install react-bootstrap --save
        - npm install react-horizontal-scrolling-menu --save
        - npm install axios --save
      script:
        - npm test



  
